# -*- coding: utf-8 -*-
"""sentencetransformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12-MM1iDpSC6w71r4eaZiH2BLn8bu3eB6
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer, util
#load the model
model = SentenceTransformer('all-MiniLM-L6-v2')
# Take input from user
text1 = input("Enter text 1: ")
text2 = input("Enter text 2: ")
# convert text into embeddings
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)
# calculate similarity
similarity = util.cos_sim(embedding1,embedding2)
# show result
print("\n similarity Score :",round(float(similarity),2))
if similarity > 0.75 :
  print("similarity Score : high")
elif similarity > 0.4 :
  print("similarity Score : medium")
else :
  print("similarity Score : low")