# -*- coding: utf-8 -*-
"""textgeneration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1442LSJExlpJk_sFaRR1Bb5oXmYv-m_9j
"""

!pip install transformers torch

from transformers import pipeline
# load text generation model (GenAI)
generator = pipeline(
    "text-generation",
    model="gpt2"
    )
# Input prompt
prompt = "Artifitical Intellige in finance will"
# generate text
result = generator(prompt, max_length=100, num_return_sequences=1)
print("AI Generated Text:")
print(result[0]['generated_text'])